### ISSUE TITLE
4 tests break if we bump version.jena from 4.8.0 to 4.9.0

### ISSUE THREAD

**Issue by tuxji** [SemanticApplicationDesignLanguage/sadl#1088]
@crapo Hi Andy, do you know why 4 tests [break](https://github.com/SemanticApplicationDesignLanguage/sadl/actions/runs/5765628604/job/15631976788?pr=1082) if we allow dependabot to bump version.jena from 4.8.0 to 4.9.0?  I have examined the tests closely and all I can determine is that the actual Jena output no longer matches the expected Jena output, although the actual Jena output still resembles the expected Jena output.  I have scanned the Jena [release announcement](https://lists.apache.org/thread/vhn0olwcmv755np52qqddn74d5hrnot8) but have not seen anything that I can point to and say that is the reason for the change.  

Will you please examine these 4 tests and let me know if we should simply update these 4 tests' expected Jena output to match the new actual output?

**Comment by crapo** [comment]
Hi John,

I'm on vacation this week and next and have no access to a computer. I'd be
happy to take a look the week after next.

Andy

**Comment by crapo** [comment]
@tuxji Hi John, looking at the output of the integration gives some clues to the problem but I'd really like to have the exact environment with the newer version of Jena in an Eclipse development environment so that I could run in a debugger. Is there some easy way to do that? I don't see that there is a branch that I could switch to that would provide that environment, but I'm a bit out of my comfort zone here.

**Comment by tuxji** [comment]
Yes, there is a branch you can check out to get the exact environment needed to reproduce the failing tests.  

The branch is:  `dependabot/maven/sadl3/com.ge.research.sadl.parent/version.jena-4.9.0`

The mvn command that the CI ran is:  `mvn -f sadl3/com.ge.research.sadl.parent/pom.xml package -Dtycho.localArtifacts=ignore`

The version of Java that the CI used is:  `Eclipse Temurin Java 17.0.8+7 (Temurin-Hotspot)`

**Comment by crapo** [comment]
@tuxji , I can reproduce the 4 test failures running Maven, but when I try to run in Eclipse to debug I don't get very far and am having trouble understanding the cause. If I try to run one of the failing tests in Eclipse, I get this error:
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine
	at org.apache.jena.atlas.lib.cache.CacheCaffeine.<init>(CacheCaffeine.java:47)
	at org.apache.jena.atlas.lib.CacheFactory.createCache(CacheFactory.java:45)
	at org.apache.jena.atlas.lib.CacheFactory.createCache(CacheFactory.java:33)
	at org.apache.jena.riot.adapters.FileManagerModelCache.setModelCaching(FileManagerModelCache.java:47)
	at org.apache.jena.riot.adapters.AdapterFileManager.setModelCaching(AdapterFileManager.java:248)
	at org.apache.jena.ontology.OntDocumentManager.setCacheModels(OntDocumentManager.java:645)
	at org.apache.jena.ontology.OntDocumentManager.setDefaults(OntDocumentManager.java:1097)
	at org.apache.jena.ontology.OntDocumentManager.<init>(OntDocumentManager.java:223)
	at org.apache.jena.ontology.OntDocumentManager.<init>(OntDocumentManager.java:209)
	at com.ge.research.sadl.builder.ConfigurationManagerForIDE.getJenaDocumentMgr(ConfigurationManagerForIDE.java:1384)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.prepareEmptyOntModel(JenaBasedSadlModelProcessor.java:2169)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1529)
........	
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.Caffeine
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 54 more
The code that references the class Caffeine is
![image](https://github.com/SemanticApplicationDesignLanguage/sadl/assets/1186278/e942e385-30ee-49dc-9090-366b21659c60)

Eclipse shows no error on the import or the reference, but if I ask it to open the declaration of Caffeine it does do so ("Current text selection cannot be opened in an editor") and I am unable to find it in the Referenced Libraries jars. 

Any suggestions?

**Comment by crapo** [comment]
BTW, the import on line 27, RemovalListener, can be opened although it isn't found in the sources in the Maven repository, which only has version 0.13.4. So maybe this is a versioning issue?

**Comment by tuxji** [comment]
OK, I realize now that we do need the other jar(s) that Jena 4.9.0 has added to the Jena jars.  I had noticed that the list of Jena jars had had more changes than just removing jena-shaded-guana.jar, but I had been hoping that the other changes weren't important.  It looks like we should add (at least) the caffeine jar to the build.properties and MANIFEST.MF (Bundle-ClassPath) in com.ge.research.jena.  When I have time (later today or tomorrow), I'll make sure to update these two files to provide all the jars that Jena depends on.

**Comment by tuxji** [comment]
@crapo I have added all the jars in com.ge.research.jena/lib to its Bundle-ClassPath and rerun the tests, but the same 4 tests still fail.  However, I've committed the changes and pushed the new commit to the `dependabot/maven/sadl3/com.ge.research.sadl.parent/version.jena-4.9.0` branch anyway so that when you run in Eclipse to debug, you shouldn't get the `java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine` exception anymore.

**Comment by crapo** [comment]
Thanks @tuxji ! Each of the four test failures was due to an assumed order of statements in a returned Jena OWL model. The order of statements changed in the new version of Jena. Since order isn't guaranteed, the tests have been modified to be order-independent. All tests pass and I've pushed to the branch.

**Comment by tuxji** [comment]
Wonderful, @crapo !  The CI job ran flawlessly, too!  

Do you think we should keep the new jars I added to Bundle-ClassPath?  I don't want to increase SADL's size unnecessarily (the jars are copied into the SADL plugin), but your IDE actually caught a NoClassFoundException during debugging, which indicates at least one jar should be added.  Did my adding the jars help you, and should I keep all the new jars?

**Comment by crapo** [comment]
Adding the jar so that I could use the Eclipse development environment was extremely helpful! I couldn't have figured out what was going on without it. As to which other jars might be needed, I have no idea. As far as I know, in the past, we've always included all of the Jena dependencies.

**Comment by tuxji** [comment]
Agreed, if we use a Jena jar, we should include all of its dependencies to be safe.  I've merged the PR and let's close this issue.  Thank you, @crapo !
