### ISSUE TITLE
"All Different" statement loses instance relationship

### ISSUE THREAD

**Issue by glguy** [SemanticApplicationDesignLanguage/sadl#447]
I'm finding that if I use a *are not the same* statement that the resulting OWL files lose the relationship between {I,J} and C. The behavior changes when I switch to `I is not the same as J.` Removing the distinctness statement altogether seems to give a different encoding.

```
uri "http://glguy.net/sadl/alldifferentexample".
C is a class.
I is a C.
J is a C.
{I,J} are not the same.
```

Is this the intended behavior?

**Comment by crapo** [comment]
@glguy, no, not the intended behavior. This is a bug that is caused by an incorrect identification of the declaration and type in the Xtext. "{I,J} are not the same." should give the exact same model as "I is not the same as J." Thanks for finding it!

**Comment by crapo** [comment]
@kittaakos , this is an error in that the definition of "I", "J" are on the lines that specify the class to which they belong, not the last line. The call to declaration extensions incorrectly returns that "I" and "J" are classes rather than individuals. If this is hard to fix we may not be able to fix it right away due to funding limits. Please proffer an opinion about how easily/quickly it might be fixed.

**Comment by crapo** [comment]
An addendum to this issue. The Jena documentation ([https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/ontology/OntModel.html](https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/ontology/OntModel.html), search for allDifferent)seems to be at odds with the W3C documentation ([https://www.w3.org/TR/owl-ref/#differentFrom-def](https://www.w3.org/TR/owl-ref/#differentFrom-def)). The former claims that allDifferent applies to classes while the W3C states clearly, and the examples support, that it applies to individuals. This issue, I believe, is rooted in the Xtext miss-typing I and J as classes and will be resolved when this is fixed, since "I is not the same as J." works as expected and uses the same code.

**Comment by kittaakos** [comment]
If I understood this issue correctly, there are two different problems here:

1. **Linking** (where `[]` represents the declaration of a SADL resource and `<>` is a ref only):

Expected:
```
uri "http://glguy.net/sadl/alldifferentexample".
[C] is a class.
[I] is a <C>.
[J] is a <C>.
{<I>,<J>} are not the same.
```

Actual:
```
uri "http://glguy.net/sadl/alldifferentexample".
[C] is a class.
<I> is a <C>.
<J> is a <C>.
{[I],[J]} are not the same.
```

----

 2. **Incorrect [concept type](https://github.com/crapo/sadlos2/blob/0aea0756404e02d831a6ba47a85fc0852c0a99eb/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/model/DeclarationExtensions.xtend#L226)**:
 - @crapo, is it possible to correctly infer the concept type from the AST only or should we use the `OntModel` instead?

**Comment by crapo** [comment]
#1's expected linking is the correct linnking.
WRT #2, I thought that if #1 were fixed #2 would be automatically fixed. I imagined that the confusion is in the logic of DeclarationExtensions, where similar constructs such as "`{<I>,<J>} are types of [C].`" or "`{<A>,<B>} are instances of [C].`" were not being differentiated properly from this current case.

**Comment by kittaakos** [comment]
> Please proffer an opinion about how easily/quickly it might be fixed.

I looked into it; the fix is not trivial. We have a list of rules to pick up definitions first before the references:

https://github.com/crapo/sadlos2/blob/238bcd4d63841e390c5037baf5d16d541b1b65be/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend#L329-L338

The order list defines the precedence of the SADL resource definitions. If I move the `5.` rule before the `1.` one, we fix this issue but break other tests.

Let me know if I should look into this further.

**Comment by crapo** [comment]
Why wouldn't this be a satisfactory solution?
'	val LocalScopeProvider localScope_01 = namedScopeProvider([resource, namespace, parentScope, importScope |
		return internalGetLocalResourceScope(resource, namespace, parentScope, importScope, true) [
			if (it instanceof SadlResource) {
				return (eContainer instanceof SadlClassOrPropertyDeclaration && eContainingFeature == SADL_CLASS_OR_PROPERTY_DECLARATION__CLASS_OR_PROPERTY && !(eContainer.eContainer instanceof SadlDifferentFrom))
					|| eContainer instanceof SadlProperty && (eContainer as SadlProperty).isPrimaryDeclaration() && eContainingFeature == SADL_PROPERTY__NAME_OR_REF;
					
			} 
			return false;
		];
	], '01');
'
I can't seem to make this code block format as code in markdown, but the change is to add this to the first element of the OR in SadlScopeProvider line 108:
`&& !(eContainer.eContainer instanceof SadlDifferentFrom)`
A SadlDifferentFrom container can never be a definition, it can only be a reference, so the modification is to not return true if the container of the SadlClassOrPropertyDeclaration is SadlDifferentFrom. With this change, all tests pass including one that started failing because I added  an error when the type of the references in the SadlDifferentFrom have OntConceptType isn't INSTANCE.

**Comment by kittaakos** [comment]
> all tests pass including one that started failing because I added an error when the type of the references in the SadlDifferentFrom have OntConceptType isn't INSTANCE.

I am not sure if I understand this part, but I created a [PR](https://github.com/crapo/sadlos2/pull/451) with your proposed change. I added a linking and an ontology concept type test.

**Comment by crapo** [comment]
Thanks Akos! Fix in next release.

**Comment by kittaakos** [comment]
> Thanks Akos!

You've [fixed](https://github.com/crapo/sadlos2/issues/447#issuecomment-634067653) the issue, I just converted into two test cases. 😊

> Fix in next release.

👍
