### ISSUE TITLE
What is the SADL syntax for durations?

### ISSUE THREAD

**Issue by Ptival** [SemanticApplicationDesignLanguage/sadl#454]
It appears SADL supports a primitive `duration` type, mapped to `xsd:duration`.

However, I have not been able to instantiate such a duration, as I have not found where the concrete syntax for those is defined.

Failed attempts:
* `... with cookingTime 20 minutes.`
* `... with cookingTime 20 mins.`
* `... with cookingTime PT20M.` (XML's XSD syntax for duration)
* `... with cookingTime "PT20M".` (idem)

**Comment by crapo** [comment]
I'm assuming that you are using the latest release of SADL V3.3. 
The SADL grammar supports units on numbers, so  the number followed by the units should not be a grammar problem. (Units with spaces or characters like "/" must be quoted.) So I assume you're getting a type checking error due to the mismatch between the range (duration) and the value, which will be a UnittedQuantity. You can cause units to be ignored in the translation to OWL and/or make type errors warnings only in the SADL Preferences. With those changes in place I'm not sure what else you want to happen.

**Comment by Ptival** [comment]
Ah, this makes sense! I understand the errors I was getting better now.

With the option you pointed me to, I can define `cookingTime` as an `int`, and type in `20 minutes` and it works as you described.

What I still don't know is, if I define `cookingTime` as a single value of type `duration`, is there anything I can write in SADL that will be translated to an appropriate `xsd:duration`?

**Comment by crapo** [comment]
Now I understand your question better. I hadn't considered this before. SADL handles xsd:date and xsd:dateTime values as strings which are then converted to Jena TypedLiterals in the method "getLiteralMatchingDataPropertyRange" in the SadlUtils class. This class uses the POJava package to convert the string to a POJava DateTime instance, which is then converted to a string which is passed to Jena to create a TypedLiteral. This method needs extension to handle xsd:duration and create the corresponding Jena TypedLiteral in the OntModel. I see that POJava doesn't appear to be actively under development but does appear to have a Duration class. Feel free to suggest a patch to fix this deficiency. Otherwise I'll consider this on my to-do list. Thanks for pointing this out!

**Comment by crapo** [comment]
This piqued my curiosity and I couldn't resist so I did some work on it. This model:

```
 CookedFood is a class described by cookingTime with values of type duration .
  Browies is a CookedFood with cookingTime 20 min.
```
now yields this OWL (which is wrong, and causes errors when processed by Jena):
`  <Issue454:CookedFood rdf:ID="Browies">
    <Issue454:cookingTime rdf:datatype="http://www.w3.org/2001/XMLSchema#duration"
    >20 min</Issue454:cookingTime>
  </Issue454:CookedFood>
`
Inputs could be "20 minutes", "20 min", ""PT23M"", etc.

What this doesn't address is type checking, which sees "20 min" as a UnittedQuantity and ""PT23M"" as a string. So this still needs a little more work.

**Comment by crapo** [comment]
Well, POJava Duration doesn't parse years so using this class would only work for durations of less than 1 year, expressed in smaller units than year. Also, the output of Duration.toString() isn't XSD syntax for duration--it's missing the leading "P" and the units are lowercase. Not finding existing code to solve this problem.

**Comment by crapo** [comment]
OK, so years and months in durations are hard and I don't find any software to do it. Checking for years or months, giving error. W, D, H, M S work. Tests added. Type checking fixed. 
Note that duration will be processed with units even when ignore units in translation is checked in preferences as this isn't a UnittedQuantity related issue.
Will be in next release.
