### ISSUE TITLE
How to configure log4j?

### ISSUE THREAD

**Issue by Ptival** [SemanticApplicationDesignLanguage/sadl#465]
When I start Eclipse and a SADL file, I get the following message in my Eclipse console:

```
log4j:WARN No appenders could be found for logger (com.ge.research.sadl.ui.preferences.SadlPreferenceStoreAccess).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Reading the linked FAQ, it appears I would need some log4j configuration file in the classpath. I have no idea how to do so for something that comes as an Eclipse plug-in.

**Comment by crapo** [comment]
This message has been around for years and a number of people have tried to fix it. It appears to be a fairly illusive goal. I think the issue comes from the multiple loggers that are used by different Open Source libraries that are used in SADL. To answer your question more directly, I believe that you can set VM arguments in the eclipse.ini file, and the form of the argument you want is, for example, 
-Dlog4j.configuration=file:/C:/.../log4j.properties

**Comment by Ptival** [comment]
Thanks, at least it's good to know that this message is not a source of concern.

I started paying attention to it because I started getting those (awful) error messages:

```
Jena TDB - See error log for details
```

And have so far been unsuccessful at finding where this error log may be.

**Comment by crapo** [comment]
Are you using Jena TDB for persistence? I don't know if that works in Version 3; it hasn't been tested.

**Comment by Ptival** [comment]
Oh, this was likely the issue, I must have changed this at some point. Back to the RDF/XML-ABBREV now and those errors are gone, thanks!
