### ISSUE TITLE
Incorrect error marking in SADL query

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#483]
In a SADL query like:

    Ask: select distinct rq, sid where rq is a REQUIREMENT and rq Rq:satisfies sid.

where there are imports with 2 definitions of "satisfies" using "Rq:satisfies" to identify which one is meant. However the following error message is shown:

    Unexpected error finding property 'Rq:Rq:satisfies' in ontology, cannot validate

**Comment by crapo** [comment]
@kittaakos , I think I might need some help with this as it appears to be in the name returned by the DeclationExtensions. The attached project illustrates this. Import, open the test.sadl file. The property 'weight' is ambiguous here. The first query has the error about ambiguity. The 3rd query is the new functionality I was working on that shows an error for an opaque SPARQL query string. The 2nd of the 3 queries has this error:

`Unexpected error finding property 'model1:model1:weight' in ontology, cannot validate`

The call to DeclarionExtensions to get the concrete name in JenaBasedSadlModelprocessor.java, line 7856, returns model1:weight even through trim prefix is true. This results in the model processor trying to find property 'model1:model1:weight' and results in the error message.
[GH-483-484.zip](https://github.com/crapo/sadlos2/files/4990769/GH-483-484.zip)

**Comment by kittaakos** [comment]
I am blocked by https://github.com/crapo/sadlos2/issues/493.

**Comment by kittaakos** [comment]
> he call to DeclarionExtensions to get the concrete name in JenaBasedSadlModelprocessor.java, line 7856, returns model1:weight even through trim prefix is true. This results in the model processor trying to find property 'model1:model1:weight' and results in the error message.
> [GH-483-484.zip](https://github.com/crapo/sadlos2/files/4990769/GH-483-484.zip)

What is the expected concrete name? Is it `weight`? I am not sure if we need to change anything in the declaration extensions. However, you can make this work on the model processor part, and use the declarations instead of the refs to acquire the concrete name.

Here is a diff that fixes the issue without changing the underlying logic all over the application:
```diff
diff --git a/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java b/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
index 241a105d..517b3f43 100644
--- a/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
+++ b/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
@@ -7853,7 +7853,7 @@ public class JenaBasedSadlModelProcessor extends SadlModelProcessor implements I
 
        public Node processExpression(SadlResource expr) throws TranslationException {
                checkForInvalidAnnotation(expr);
-               String nm = getDeclarationExtensions().getConcreteName(expr);
+               String nm = getDeclarationExtensions().getConcreteName(getDeclarationExtensions().getDeclaration(expr));
                String ns = getDeclarationExtensions().getConceptNamespace(expr);
                String prfx = getDeclarationExtensions().getConceptPrefix(expr);
                OntConceptType type;
```

Let me know what you think.

**Comment by crapo** [comment]
I had wondered about doing that. The reason I hesitated was because the call down in the innards of getConcreteName seemed to be returning the name with a prefix even thought the flag trimPrefix (or something like that) was true.
I'm all for not giving the system a big jolt so will go with your suggestion.

I do still wonder under what circumstance should a call to getConcreteName return the qualified name (with prefix) and if this issue will be found elsewhere....

**Comment by kittaakos** [comment]
> The reason I hesitated was because the call down in the innards of getConcreteName seemed to be returning the name with a prefix

You're right. Let me check once more.

**Comment by kittaakos** [comment]
I have checked it, `trimPrefix` is currently implemented to work with aliases as described here:

https://github.com/crapo/sadlos2/blob/d1f960caaca17bbb15d284e64155f12909a6bda8/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/model/DeclarationExtensions.xtend#L80-L92

**Comment by crapo** [comment]
What this Javadoc does not specify is what should happen with an imported name, which is the subject of this issue. 
`uri "http://sadl.org/M1" alias m1.
Foo is a class.`
and
`uri "http://sadl.org/M2" alias m2.
p1 describes m1:Foo with values of type int.`

For this example, if there were a call to processExpression(SadlResource expr (as happens in the QueryStatement example provided above) what should the calls to getConcreteName return, "Foo" or "m1:Foo"?

This issue is resolved by calling extensions.getConceptUri(sr) rather than getting the concrete name and the namespace and putting them together. But for sake of completeness, it might be nice to document what the expected return is for the method.

**Comment by kittaakos** [comment]
> to document

PR: https://github.com/crapo/sadlos2/pull/494
