### ISSUE TITLE
Need help with qualified cardinality syntax

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#509]
I am trying to redo the qualified cardinality test in SADL 3.4 syntax that was present in the openge project SadlModels/TestGeSadl/ValidateWithQualifiedCardinality.sadl. Could you help with getting the syntax correct for this SADL 
file.
[ValidateWithQualifiedCardinality.sadl.txt](https://github.com/crapo/sadlos2/files/5151643/ValidateWithQualifiedCardinality.sadl.txt)

**Comment by crapo** [comment]
Here's an export of a project with a modified file that does validation of qualified, max qualified, and min qualified property restrictions. It also illustrates using concepts from OWL and RDF explicitly in rules. A modification to SADL model processing should also be implemented so that the OWL and RDF fragments are imported into the generated OWL file as they a) are not needed, and b) might cause problems.
[GH-509.zip](https://github.com/SemanticApplicationDesignLanguage/sadl/files/5596621/GH-509.zip)

@AbhaMoitra , I don't think this is an issue for you at present, but am closing issues so wanted to document this. I'll also add this to the new TestSadl3IDE project.

**Comment by AbhaMoitra** [comment]
@crapo : yes, I do not think this affects my current projects. I'll take a look at exported project at a later point.

**Comment by AbhaMoitra** [comment]
@crapo: we were just in the process of revising cardinality restrictions in RACK (and we have a code freeze this weekend). Earlier by default we were using "with values of type". So right now should we use 
     p1 describes A1 with values of type A2.
     p1 describes A1 with at most 1 value.
 or should we use
    p1 describes A1 with at most 1 value of type A2.

I think we should use the first alternative? Is that being handled correctly at this point?

**Comment by crapo** [comment]
@AbhaMoitra , that depends on what you want to say. The issue identified in #576 is only with "p1 describes A1 with a single value of type A2."

"p1 describes A1 with values of type A2." gives p1 the domain A1 and range A2.

"p1 describes A1 with at most 1 value." sets a maxCardinality restriction on property p1 for class A1.

I agree that this combination is probably the safest for now.

"p1 describes A1 with at most 1 value of type A2." sets a maxQualifiedCardinality restriction: instances of A1 can have at most 1 value of type A2 for property p1. This probably doesn't make p1 an object property in the current release but this will be fixed with the solution to #576. (Note that it could have been defined as an object property elsewhere, e.g., "p1 is a property with values of type class.") 

Fixing #576 will make clarifying all of this much easier.

**Comment by crapo** [comment]
@AbhaMoitra , can this issue be closed? The changes of #576 have been merged.
