### ISSUE TITLE
Difficulty generating JavaDoc for SadlServer

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#574]
@tuxji , when I try to generate JavaDoc for the com.ge.research.sadl.server project, and select the two subprojects, I get these errors and nothing is generated. I suppose that something somewhere indicates Java 1.3? But I don't find it. I do not find any solution that makes sense googling the errors. Ideas?

error: Source option 1.3 is no longer supported. Use 6 or later.
error: Target option 1.3 is no longer supported. Use 1.6 or later.
2 errors

**Comment by tuxji** [comment]
@crapo , here are some [instructions](https://www.codejava.net/ides/eclipse/how-to-generate-javadoc-in-eclipse) that will show you how to generate javadocs in Eclipse (which I assume is where you are getting your errors).  You can also google how to run javadoc from the command line and that should work fine too.

**Comment by crapo** [comment]
@tuxji , those instructions are better than the ones I was using, but the result after carefully following them is exactly the same error. I also tried running from cmd line. Can you create JavaDocs for the com.ge.research.sadl.server subprojects (sadlserver-api and sadlserver-impl together)? I wonder if this has something to do with using OpenJDK. I've not had this problem in the past, but it's been a while since I've generated JavaDocs.

**Comment by tuxji** [comment]
@crapo I've made changes to the poms and fixed some of the javadoc comments so that Maven can generate javadocs for the com.ge.research.sadl.server subprojects.  Please read the description in my pull request #575 (I already merged it) for more details.  If you would like to generate javadocs for other subprojects, you may need to fix some more errors.  Please close this issue when you verify you're able to generate these javadocs.

**Comment by crapo** [comment]
JavaDocs for SadlServer generated and added to documentation. How to generate for documentation also documented.
