### ISSUE TITLE
Does SADL work with xtext 2.24

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#592]
@tuxji , @crapo.
A DARPA ARCOS performer is trying to use SADL and he see the following error in installing SADL. 

![image](https://user-images.githubusercontent.com/28540315/102727163-28dca600-42f2-11eb-8f3f-6bd289308205.png)

He also reported "When I search explicitly in my Installed Software, “osgi” does not show up, but when I search for “osgi” in Plug-ins, I see “OSGi System Bundle” version 3.16.100, but it has the Plug-in ID of “org.eclipse.osgi” and not “osgi.bundle”. As for “xtext”, I see that I have 2.24.0 installed and not 2.22.0." His installation details are as follows

![image](https://user-images.githubusercontent.com/28540315/102727231-8113a800-42f2-11eb-9b83-b897cb63ea00.png)

**Comment by crapo** [comment]
@AbhaMoitra , the issue that pegged SADL to Xtext 2.21 was addressed in PR "Updated to Xtext 2.23.0 #532" by Akos, which was merged into development by @tuxji on December 1. However, there has not been a SADL release since Oct 21, so assuming that the DARPA ARCOS performer is trying to install from releases, this error is entirely expected. @agabaldon , @weisenje , @tuxji , my working assumption is that only one of you will create new releases.

**Comment by crapo** [comment]
@AbhaMoitra , of course the other approach to this problem is to have the person follow the installation instructions. "This release is only compatible with Xtext 2.21, which is included in Eclipse for Java and DSL Developers 2020-03. It is recommended that it be used with Eclipse 2020-03." Not clear why they presumably ignored this.

**Comment by tuxji** [comment]
@crapo Making a release is easier to do now that I have written the following two GitHub Actions workflows:

1) Every push to a branch in the GithHub repository will run a continuous workflow which will build and attach an installable zip file built to that push's run in the Actions tab.  Anyone can download that zip file if they want to test the latest SADL on their machine; just look for the most recent run in the Actions tab and click on that run to find the zip file.
2) When someone has tested the latest zip file and verified it is in a releasable state, then all we have to do is to go to the Releases page, click the Create New Release button, write some release notes, and click the Publish button.  Publishing the release will run a release workflow which will build and attach an installable zip file to the release page too.  

I don't mind clicking the Create New Release button, but I would need @crapo to help write some release notes for the new release.  If you look at the 69 commits to development since the last release, there are some major changes in there so this new release should be a major new release (3.5.0) and someone should test the most recently built installable zip file first.

**Comment by AbhaMoitra** [comment]
@tuxji @crapo  I can do some testing. The latest zip file I found is : sadl-dependabot-npm_and_yarn-sadl3-com.ge.research.sadl.parent-theia-sadl-extension-ini-1.3.7.zip. Is that correct? I am not able to install SADL from this and I have Xtext 2.21 in my new eclipse so how do I get newer version of xtext?

**Comment by crapo** [comment]
@AbhaMoitra , I don't know where the zip file is, but I recommend that you use a version of Eclipse newer than 2020-03 so that it doesn't have Xtext 2.21 in it. Since your user apparently had Xtext 2.24 in his, I'm assuming that he is probably using a version of Eclipse that is quite new.

**Comment by AbhaMoitra** [comment]
@crapo : Thanks. I installed a newer eclipse and it has xtext 2.24.

**Comment by crapo** [comment]
@tuxji , @AbhaMoitra , I updated version to 3.5.0. Incidentally, I believe that requires changes to 50+ files. All tests pass and I pushed to development.

**Comment by tuxji** [comment]
SADL Version 3.5.0 is now available at <https://github.com/SemanticApplicationDesignLanguage/sadl/releases/tag/v3.5.0-20201224>.

**Comment by AbhaMoitra** [comment]
@tuxji @crapo - just a note. I had eclipse with xtext 2.24; then when I then installed SADL Version 3.5.0, the xtext version became 2.23. My VERDICT-STEM project is working fine.

@crapo : Also, I am trying to install DARPA ASKE and the instructions in https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/wiki/Installation-Instructions-for-GE-ASKE-System-Eclipse-Plug-ins say "The latest release of SADL that is BEFORE the release data of the GE ASKE System to be installed in the next step should be selected." Now, GE ASKE release version I see is dated June 29, 2020. So should I install this GE ASKE release or not - please advise.

**Comment by crapo** [comment]
@AbhaMoitra , I can build a new release of ASKE which will be compatible with the 3.5.0 release of SADL. I'll do that early next week.
