### ISSUE TITLE
META-INF/services folder is no longer there

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#639]
I added two builtins in com.ge.research.sadl.jena-wrapper-for-sadl/com.ge.research.jena.reasoner.builtin but the META-INF/services folder is gone. How do I do the equivalent of adding builtins lines to org.apache.jena.reasoner.rulesys.Builtin ?

**Comment by tuxji** [comment]
The META-INF/services folder was redundant.  You don't have to do anything after creating the builtins because a plugin in the Maven pom finds the builtins, lists them, and generates the META-INF/services files automatically during the Maven build.  Please IM me if you want more details or have questions.

**Comment by agabaldon** [comment]
Got it. That's good.
