### ISSUE TITLE
Can no longer create an update that installs in Eclipse 2020-12

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#646]
When I create an update and then try to use to update SADL in Eclipse 2020-12 (or other versions of Eclipse) or to install in a fresh Eclipse for Java Developers 2020-12, I always get an error now:
loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @31d88eac wants to load interface com.google.common.base.Function. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @5b2347f0. (com.google.common.base.Function is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5b2347f0, parent loader 'platform') (occurred in com.ge.research.sadl.ui.SADLExecutableExtensionFactory)
@agabaldon , @tuxji , does anyone else have this issue with generated updates?

**Comment by tuxji** [comment]
How are you generating the update - from Eclipse itself, from the command line with a Maven command, or from GitHub Actions' continuous integration workflow?  If it's the last one, I can download the update (zip file) and try updating SADL in my Eclipse to see if I get the same error too.  I didn't get any error when installing updates generated by CI from the development branch.  You can download the most recent development branch update from [here](https://github.com/SemanticApplicationDesignLanguage/sadl/suites/2402478549/artifacts/51121135).

**Comment by crapo** [comment]
@tuxji , that is a point I hadn't considered. I'm generating the update by running a Maven install -U on the entire set of projects. I was trying to make sure that the service loader was working when the plugins are installed before pushing to github. Should an update so created still work?

**Comment by tuxji** [comment]
Yes, with a caveat.  You should use Java 11, clean first, and use the same Maven command that the CI workflow uses with an additional `-Dtycho.localArtifacts=ignore` option because you've been running `mvn install` in the past which means the Tycho build must be told NOT to reuse previously built artifacts from your .m2 repository:

```shell
cd sadl3/com.ge.research.sadl.parent/
mvn clean
mvn package -Dtycho.localArtifacts=ignore
```

Unless you have an application which uses some SADL jars (like the SADL Server jar and its transitive dependencies), there's no reason to install SADL jars into your .m2 repository.  The "mvn package" command will build the zip file update just fine without spending extra time unnecessarily copying jars and that zip file into your .m2 repository.

**Comment by agabaldon** [comment]
@Crapo, yes, I have that issue. I can no longer install SADL updates. I reported that 
 here: https://github.com/SemanticApplicationDesignLanguage/sadl/pull/631

**Comment by Ptival** [comment]
I'm also encountering the "loader constraint violation" error.

Has there been progress on figuring this one out? Or known workarounds?

**Comment by crapo** [comment]
@tuxji , @Ptival , I just confirmed that downloading the latest update ZIP from the CI builds does not install into Eclipse 2020-12 Java. I get the error "loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @78c24993 wants to load interface com.google.common.base.Function. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @63513c1c. (com.google.common.base.Function is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @63513c1c, parent loader 'platform') (occurred in com.ge.research.sadl.ui.SADLExecutableExtensionFact..."

**Comment by crapo** [comment]
@tuxji , note that I have the same error when I download the exact update that you linked to above. The error does not appear until I try to open a file in the SADL editor.

**Comment by crapo** [comment]
@Ptival , I have confirmed that I can install the latest update (one that I built) successfully by doing the following.
1. Download and extract Eclipse 2020-12 for Java Developers.
2. Install Xtext 2.24 and its related components by installing new software and pasting in the URL http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.24.0
3. Install the latest SADL build by installing new software and adding the archive file with the latest SADL build.

**Comment by Ptival** [comment]
I am trying this again now and the given solution does not work for me.

When installing the latest SADL build, it claims to be incompatible with Xtext 2.24 and wants to uninstall it (reverting to 2.23).

<img width="920" alt="image" src="https://user-images.githubusercontent.com/478606/130494849-b76d1fcf-b395-4387-9340-c1921fc024a3.png">

**Comment by crapo** [comment]
@Ptival , I redid my test of the above and it worked without complaint or error in my Linux environment. If, when you install SADL, it wants to revert to Xtext 2.23, then I expect that you are not using a new build of the SADL installation ZIP file. 
@tuxji , @agabaldon , @AbhaMoitra : someone needs to build a new release and add it to releases or Robert will have to build his own. I believe that we have established that he cannot access the automatic builds that are created when new code is pushed to development.

**Comment by AbhaMoitra** [comment]
@agabaldon : could you build a new release? I know @tuxji is busy on something.

**Comment by agabaldon** [comment]
How come the update zip file name now is com.ge.research.sadl.update-3.5.0-SNAPSHOT.zip instead of something like com.ge.research.sadl.update-3.5.0.202104011344.zip ? It is also 3X the size of old updates. Am I looking in the wrong directory? I'm looking in com.ge.research.sadl.parent/com.ge.research.sadl.update/target

**Comment by tuxji** [comment]
I'll build a new release once I finish some changes to dockerize a command-line SADL.  

Yes, the update zip file has changed its name and become 3X bigger due to recent changes.  We now include all Eclipse features/plugins used by SADL in the update zip to make it easier to install SADL in any Eclipse IDE (even those which don't have Xtext or other things needed by SADL).

**Comment by agabaldon** [comment]
I added a (pre)release before I saw your message.

**Comment by tuxji** [comment]
@Ptival I've enhanced the SADL GitHub release workflow so it also builds ready to run out of the box SADL-Eclipse products for Linux, MacOS, and Windows platforms as well as the zip file archive of the SADL update p2-repository.  I've just used this automated workflow to build a new SADL release ([SADL Version 3.5.0 build 20210825](https://github.com/SemanticApplicationDesignLanguage/sadl/releases/tag/v3.5.0-20210825)).  You can install a functional SADL IDE simply by unzipping the appropriate Eclipse product for your platform, running its executable launcher binary, and then importing a SADL project into your SADL-Eclipse's workspace.  I believe we can close this issue after you confirm your problem is resolved this way.

**Comment by tuxji** [comment]
A new SADL release is available now. This release corrects SADL's explicitly versioned dependency on Xtext 2.24.0. SADL should now install in any recent Eclipse version, not only Eclipse 2020-12, and use any recent Xtext version compatible with that Eclipse version, not only Xtext 2.24.0. This release should fix this issue's installation problems, I believe.

**Comment by crapo** [comment]
@tuxji , @agabaldon , I believe this should be closed as none of the issues remain. Do you agree?

**Comment by tuxji** [comment]
I agree, closing now.

**Comment by AbhaMoitra** [comment]
@tuxji @crapo @agabaldon : I agree that it can be closed.
