### ISSUE TITLE
Unexpected results with defaults

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#661]
I'm trying to use defaults and I'm getting unexpected results. Here's a simple example:

`Thing is a class.
p0 describes Thing with values of type int.
p0 of Thing has default 0.
p1 describes Thing with values of type int.
p1 of Thing has default 0.
i1 is a Thing.

Rule r1
if	x p0 0 then x p1 1.

Ask: select val1 where x is a Thing and x p1 val1.`

The answer I get is:

`"val1"
     "1"
     "0"`

I tried adding level to defaults and stage to the rule but I could not get it to work and answer only "1".

**Comment by crapo** [comment]
@agabaldon , the problem here is that you have default values for both p0 of Thing and p1 of Thing at the same default level. So inference runs and rule r1 cannot fire. Then the first level defaults are applied and both p0 of i1 and p1 of i1 are given their default values of 0. Then rule r1 fires giving p1 of i1 value 1.

What you need to do is put the default values for p0 of Thing and p1 of Thing at different levels:
` Thing is a class.
p0 describes Thing with values of type int.
p0 of Thing has default 0.
p1 describes Thing with values of type int.
p1 of Thing has level 2 default 0.
`
Then you will get just the value 1 for p1 of i1:
Query: select ?val1 where {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/GH-661.sadl#Thing> . ?x <http://sadl.org/GH-661.sadl#p1> ?val1}
     "val1"
     "1"

**Comment by crapo** [comment]
Note that I did see some anomalies where the correct translator wasn't initially being retained. That wasn't the issue you report here though so I'll address that separately.

**Comment by agabaldon** [comment]
I see. That works. Looks like the first level defaults run before any rules, correct?

**Comment by crapo** [comment]
No, inference is run with the first user-defined rules, if there are any. When all possible first-level inferences are drawn, the next level rules are added, be they from defaults or rule stages. See http://semanticapplicationdesignlanguage.github.io/sadl/DefaultValues.html.

**Comment by agabaldon** [comment]
But the rule in the example fires, so it has to be applied after the default on p0?

**Comment by crapo** [comment]
An reasoner is created which loads the user-defined rule. This rule's conditions aren't met so the rule does not fire. In the modified case where the two defaults aren't at the same level, the rule for the stage 0 default (p0 of Thing) is added to the rule set so now there are two rules. The default rule fires adding triple <i1 p0 0> to the kbase. Now the user-defined rule's conditions are met by <i1 p0 0> so this rule fires, adding <i1 p1 1> to the kbase. Next the level 2 default rule (p1 of Thing) is added to the rule set so there are 3 rules. However, since i1 has a value of p1, this rule does not fire. I think this is explained in the reference previously provided, http://semanticapplicationdesignlanguage.github.io/sadl/DefaultValues.html.

**Comment by crapo** [comment]
@agabaldon , is there still an issue here to be addressed?

**Comment by agabaldon** [comment]
No. But a comment: the usual interpretation of a default is that the variable/predicate has the default value until at any point/level any other statement/rule explicitly assigns a different value. So, since I find it hard to remember what default means in SADL, I decided not to use defaults and only use staged rules, whose meaning is easier to remember for me.
So, closing this...

**Comment by crapo** [comment]
@agabaldon , is SADL's behavior significantly different from this? A default value is specified for a given property of any instance of a given class. The implementation of default value is a staged rule that assigns a value to that property of any instances of that class. After inference has done what it can, the default rules assign a value if one isn't already assigned and then inference is run again. If this gives different behavior than "the usual interpretation of a default", please try to explain the difference. Thanks!

**Comment by agabaldon** [comment]
Roughly, the normal understanding of defaults is that the default value is overridden by any rule that explicitly assigns a different value at any point of the inference process. In my original example above, intuitively val1 should only have value 1. Even if rule r1 were level n it would still defeat the default if the rule fires. I'm not saying that how inference is currently done is wrong, I'm just saying that my intuitive understanding of the example is different from the results I get. With staged rules, my intuitive understanding corresponds to the results, so I find them more intuitive to use.
