### ISSUE TITLE
SADL-Eclipse exits without any error message when no JDK is installed

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#906]
@agabaldon , @tuxji , moving this discussion from email to github. 
I decided to take a naive approach so downloaded https://github.com/SemanticApplicationDesignLanguage/sadl/releases/download/v3.5.0-20220210/sadl-eclipse-win32.win32.x86_64-v3.5.0-20220210.zip and unpacked it on a Windows 11 laptop that has not had Eclipse installed on it. When I run eclipse.exe nothing happens. From a cmd window even, there is no feedback and nothing happens. I imagine maybe Java has to be pre-installed? But I'm surprised that there is no error message.

**Comment by tuxji** [comment]
I downloaded the same zip, unpacked it on my laptop (which has had the JDK installed on it), and the usual Eclipse windows appeared when I ran eclipse.exe.  I don't have a machine to test what happens when no JDK is installed on the machine, but I'm surprised too that there is no error when no Java virtual machine is installed.  The SADL product configuration file probably needs some kind of change.  I'll change this issue's title to say "SADL-Eclipse exits without any error message when no JDK is installed."

**Comment by tuxji** [comment]
I looked at this issue yesterday and found out it still happens, but affects only Windows.  If I run sadl-eclipse on Linux, I will get an error message telling me I do not have java in my PATH.  But if I run sadl-eclipse on Windows, the launcher just exits silently.  However, if I edit sadl-eclipse's eclipse.ini, remove the line "--launcher.suppressErrors", and run sadl-eclipse again, the launcher does pop up an error message dialog telling me I do not have javaw.exe in my current PATH.  I checked sadl.product and I also found "--launcher.suppressErrors" defined in it as well.  I checked sadl.product's git log history and I found out I'd added that argument to it in the following commit over 1 year ago:

```
commit e33ae9457457e69724df147705eccda8e06a28c7
Author: John Interrante <interran@research.ge.com>
Date:   Fri Oct 22 10:31:00 2021 -0400

    Make SADLCli find and report errors finally
    
    MANIFEST.MF - Allow SADLCli to import org.apache.log4j.
    
    SADLCli.java - Give up on finding error markers (we still need to
    figure out why they're not being added to the project).  Make
    isProjectSuccessfullyBuilt and accumulateErrorMarkers call
    XtextResourceSet's getErrors method instead.  Use Set instead of List
    to avoid duplication when accumulating errors to print.  Configure
    org.apache.log4j programmatically to suppress initialization warning
    and redefine eclipse.exitdata system property to suppress extra
    messages from Eclipse launcher when SADLCli returns a non-zero exit
    code.
    
    sadl.product - Stop Eclipse launcher from popping up an error message
    dialog when SADLCli returns a non-zero exit code.
```

Since I had added "--launcher.suppressErrors" to improve SADLCli's usability on Windows, I think it's safer to keep it there than to remove it.
